# Generated by Django 5.2.5 on 2025-08-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200, verbose_name='Действие')),
                ('place', models.CharField(help_text='Введите место, где будет выполняться привычка.', max_length=200, verbose_name='Место')),
                ('time', models.DateTimeField(blank=True, help_text='Введите время выполнения привычки. Если привычка выполняется несколько раз в день, укажите также конечное время. Только для полезных привычек!', null=True, verbose_name='Время выполнения привычки')),
                ('is_pleasant', models.BooleanField(help_text='Отметьте, является ли привычка приятной. Только приятные привычки могут быть наградой для полезных.', verbose_name='Приятная привычка')),
                ('periodicity', models.CharField(blank=True, choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('biweekly', 'Раз в 2 дня'), ('triweekly', 'Раз в 3 дня')], default='daily', help_text='Выберите, как часто должна выполняться полезная привычка. Минимум раз в неделю! Только для полезных привычек!', max_length=20, null=True, verbose_name='Частота выполнения')),
                ('bonus', models.CharField(blank=True, help_text='Введите Вознаграждение за выполнение привычки.', max_length=200, null=True, verbose_name='Награда')),
                ('time_activ', models.PositiveIntegerField(help_text='Введите время на выполнение привычки в секундах. Не более 2 минут (120 секунд).', verbose_name='Необходимое время')),
                ('is_public', models.BooleanField(help_text='Выберите, будут ли пользователи видеть вашу привычку.', verbose_name='Публичная привычка')),
            ],
        ),
    ]
