# Generated by Django 5.2.6 on 2025-09-21 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Week",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("day", models.CharField(max_length=3, verbose_name="день недели")),
            ],
        ),
        migrations.RemoveField(
            model_name="habit",
            name="bonus",
        ),
        migrations.RemoveField(
            model_name="habit",
            name="periodicity",
        ),
        migrations.RemoveField(
            model_name="habit",
            name="time_activ",
        ),
        migrations.AddField(
            model_name="habit",
            name="end_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Введите время, когда нужно в последний раз за день выполнить привычку. Только для полезных привычек, которые выполняются несколько раз в день!",
                null=True,
                verbose_name="Время окончания",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("m h * * *", "каждую минуту"),
                    ("m */5 * * *", "каждые 5 минут"),
                    ("m h * * 1-5", "каждый будний день"),
                    ("m h d * *", "каждый месяц"),
                    ("m h * * 0", "каждое воскресенье"),
                    ("m h * * *", "каждый день"),
                    ("m h d * 1-5", "каждый будний день месяца"),
                    ("m h * * 1", "каждый понедельник"),
                    ("m h * * 2", "каждый вторник"),
                    ("m h * * 3", "каждую среду"),
                    ("m h * * 4", "каждый четверг"),
                    ("m h * * 5", "каждую пятницу"),
                    ("m h * * 6", "каждую субботу"),
                    ("m h * * 0-6", "каждую неделю"),
                ],
                default="m h * * *",
                help_text="Выберите, как часто нужно выполнять полезную привычку. ВНИМАНИЕ! Полезная привычка должна выполняться как минимум раз в неделю. Только для полезных привычек!",
                null=True,
                verbose_name="Частота выполнения ",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                blank=True,
                help_text="Введите вознаграждение за выполнение привычки.",
                max_length=200,
                null=True,
                verbose_name="Вознаграждение",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="time_needed",
            field=models.PositiveIntegerField(
                default=120,
                help_text="Введите время, необходимое для выполнения привычки, в секундах = 120 секунд.",
                verbose_name="требуемое время",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="action",
            field=models.CharField(
                help_text="Введите действие, которое нужно выполнить.", max_length=200, verbose_name="Действие"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_pleasant",
            field=models.BooleanField(
                help_text="Выберите, является ли привычка приятной. Только приятные привычки могут служить вознаграждением для полезных привычек.",
                verbose_name="Полезня или нет",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_public",
            field=models.BooleanField(
                help_text="Является ли привычка публичной или приватной?", verbose_name="Статус публикации"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="place",
            field=models.CharField(
                help_text="Введите место, где вы будете выполнять.", max_length=200, verbose_name="Место"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите связанную приятную привычку (в качестве вознаграждения). Только для полезных привычек!",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="habits.habit",
                verbose_name="Связанная привычка",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.DateTimeField(
                blank=True,
                help_text="Введите время, когда нужно выполнять привычку. Если привычка выполняется несколько раз в день, нужно также указать время окончания.",
                null=True,
                verbose_name="Время",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="habits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="days_of_week",
            field=models.ManyToManyField(
                blank=True,
                help_text="Выберите конкретные дни, когда нужно выполнять полезную привычку.",
                to="habits.week",
                verbose_name="Дни недели",
            ),
        ),
    ]
